import { useEffect,useState } from 'react'
import { api } from '../api/http'
import { baixarRelatorioComissoes,detalharComissao,listarPeriodosComissoes,resumirComissoes } from '../api/comissoes'
import type { CalendarioPorto,Comissao,Motorista,ResumoComissao } from '../types/modelos'
import { data,moeda } from '../utils/formatadores'

export default function ComissoesPage(){
  const [periodos,setPeriodos]=useState<CalendarioPorto[]>([]),[motoristas,setMotoristas]=useState<Motorista[]>([]),[periodoId,setPeriodoId]=useState(0),[motoristaId,setMotoristaId]=useState(0),[itens,setItens]=useState<ResumoComissao[]>([]),[detalhe,setDetalhe]=useState<Comissao|null>(null),[erro,setErro]=useState('')
  useEffect(()=>{Promise.all([listarPeriodosComissoes(),api<Motorista[]>('/api/motoristas')]).then(([p,m])=>{setPeriodos(p);setMotoristas(m);const atual=[...p].reverse().find(x=>x.ativo)??p.at(-1);if(atual)setPeriodoId(atual.id)}).catch(e=>setErro(e.message))},[])
  useEffect(()=>{if(periodoId)resumirComissoes(periodoId,motoristaId||undefined).then(setItens).catch(e=>setErro(e.message))},[periodoId,motoristaId])
  async function abrir(id:number){try{setDetalhe(await detalharComissao(id,periodoId))}catch(e){setErro((e as Error).message)}}
  return <div className="page-enter commission-page"><header className="page-heading"><div><span className="eyebrow">Equipe e pagamentos</span><h1>Comissões</h1><p>Conferência auditável das OS pagas e alimentações aprovadas.</p></div><button className="button button-ghost" disabled={!periodoId} onClick={()=>void baixarRelatorioComissoes(periodoId)}>Exportar CSV</button></header>{erro?<div className="form-alert">{erro}</div>:null}
    <section className="panel"><div className="ledger-filters"><label><span>Período financeiro</span><select aria-label="Período financeiro" value={periodoId||''} onChange={e=>setPeriodoId(Number(e.target.value))}><option value="">Selecione</option>{periodos.map(p=><option key={p.id} value={p.id}>{p.descricao} · {data(p.competenciaInicio)} a {data(p.competenciaFim)}</option>)}</select></label><label><span>Funcionário</span><select value={motoristaId||''} onChange={e=>setMotoristaId(Number(e.target.value))}><option value="">Todos</option>{motoristas.map(m=><option key={m.id} value={m.id}>{m.nome}</option>)}</select></label></div>
      <div className="table-scroll"><table><thead><tr><th>Funcionário</th><th>Serviços pagos</th><th>Produção paga</th><th>Comissão 20%</th><th>Alimentação</th><th>Líquido</th><th/></tr></thead><tbody>{itens.map(item=><tr key={item.motoristaId}><td><strong>{item.funcionario}</strong></td><td>{item.quantidadeServicosPagos}</td><td>{moeda(item.producaoPaga)}</td><td>{moeda(item.comissaoBruta)}</td><td>{moeda(item.alimentacaoAprovada)}</td><td className={item.liquido<0?'negative':'positive'}><strong>{moeda(item.liquido)}</strong></td><td><button className="table-action" onClick={()=>void abrir(item.motoristaId)}>Detalhar</button></td></tr>)}</tbody></table></div></section>
    {detalhe?<div className="modal-backdrop"><section className="modal commission-detail" role="dialog" aria-modal="true" aria-label={`Comissão de ${detalhe.funcionario}`}><header><div><span className="eyebrow">{detalhe.periodo}</span><h2>{detalhe.funcionario}</h2></div><button aria-label="Fechar" onClick={()=>setDetalhe(null)}>×</button></header><div className="porto-detail-summary"><span>Produção<strong>{moeda(detalhe.producaoPaga)}</strong></span><span>Comissão<strong>{moeda(detalhe.comissaoBruta)}</strong></span><span>Alimentação<strong>{moeda(detalhe.alimentacaoAprovada)}</strong></span><span>Líquido<strong>{moeda(detalhe.liquido)}</strong></span></div>
      <h3>Serviços que formam a comissão</h3><div className="table-scroll"><table><thead><tr><th>OS</th><th>Atendimento</th><th>OP</th><th>Valor</th><th>Comissão</th></tr></thead><tbody>{detalhe.servicos.map(s=><tr key={s.id}><td>{s.numeroOs}</td><td>{data(s.dataAtendimento)}</td><td>{s.numeroOp}</td><td>{moeda(s.valorServico)}</td><td>{moeda(s.comissaoServico)}</td></tr>)}</tbody></table></div>
      <h3>Alimentações do período</h3><div className="table-scroll"><table><thead><tr><th>Data</th><th>Valor</th><th>Situação</th><th>Observação</th></tr></thead><tbody>{detalhe.alimentacoes.map(a=><tr key={a.id}><td>{data(a.data)}</td><td>{moeda(a.valor)}</td><td>{a.aprovada?'Aprovada':a.situacao.toLowerCase()}</td><td>{a.observacoes||'—'}</td></tr>)}</tbody></table></div>
    </section></div>:null}
  </div>
}
