import { useEffect,useState,type FormEvent } from 'react'
import { listarPeriodosComissoes,obterMinhaComissao,registrarAlimentacao } from '../api/comissoes'
import type { CalendarioPorto,Comissao } from '../types/modelos'
import { data,moeda } from '../utils/formatadores'

export default function MinhaComissaoPage(){
  const [periodos,setPeriodos]=useState<CalendarioPorto[]>([]),[periodoId,setPeriodoId]=useState(0),[comissao,setComissao]=useState<Comissao|null>(null)
  const [erro,setErro]=useState(''),[mensagem,setMensagem]=useState(''),[salvando,setSalvando]=useState(false)
  useEffect(()=>{listarPeriodosComissoes().then(lista=>{setPeriodos(lista);const atual=[...lista].reverse().find(x=>x.ativo)??lista.at(-1);if(atual)setPeriodoId(atual.id)}).catch(e=>setErro(e.message))},[])
  useEffect(()=>{if(periodoId)obterMinhaComissao(periodoId).then(setComissao).catch(e=>setErro(e.message))},[periodoId])
  async function salvar(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setSalvando(true);setErro('');try{await registrarAlimentacao(String(form.get('data')),Number(form.get('valor')),String(form.get('observacoes')||''));setMensagem('Alimentação registrada e enviada para aprovação.');event.currentTarget.reset();setComissao(await obterMinhaComissao(periodoId))}catch(e){setErro((e as Error).message)}finally{setSalvando(false)}}
  return <div className="page-enter commission-page"><header className="page-heading"><div><span className="eyebrow">Área do funcionário</span><h1>Minha comissão</h1><p>Acompanhe somente seus serviços pagos e sua alimentação no fechamento Porto.</p></div><label className="month-picker"><span>Período financeiro</span><select aria-label="Período financeiro" value={periodoId||''} onChange={e=>setPeriodoId(Number(e.target.value))}><option value="">Selecione</option>{periodos.map(p=><option key={p.id} value={p.id}>{p.descricao} · {data(p.competenciaInicio)} a {data(p.competenciaFim)}</option>)}</select></label></header>
    {erro?<div className="form-alert">{erro}</div>:null}{mensagem?<div className="success-notice">{mensagem}</div>:null}
    {comissao?<><section className="metric-grid commission-metrics"><article className="metric"><span>Serviços pagos</span><strong>{comissao.quantidadeServicosPagos}</strong></article><article className="metric"><span>Total pago pela Porto</span><strong>{moeda(comissao.producaoPaga)}</strong></article><article className="metric"><span>Comissão 20%</span><strong>{comissao.aguardandoOp?'Aguardando OP':moeda(comissao.comissaoBruta)}</strong></article><article className="metric"><span>Alimentação aprovada</span><strong>{moeda(comissao.alimentacaoAprovada)}</strong><small>{moeda(comissao.alimentacaoPendente)} pendentes</small></article><article className={`metric ${comissao.liquido<0?'metric-alert':''}`}><span>Líquido</span><strong>{comissao.aguardandoOp?'Aguardando OP':moeda(comissao.liquido)}</strong></article></section>
      <section className="commission-grid"><article className="panel"><header className="panel-title"><div><span className="eyebrow">Auditoria</span><h2>Serviços pagos</h2></div></header><div className="table-scroll"><table><thead><tr><th>OS</th><th>Especialidade</th><th>Atendimento</th><th>OP</th><th>Valor</th><th>Comissão</th></tr></thead><tbody>{comissao.servicos.map(s=><tr key={s.id}><td><strong>{s.numeroOs}</strong></td><td>{s.especialidade||'—'}</td><td>{data(s.dataAtendimento)}</td><td>{s.numeroOp}</td><td>{moeda(s.valorServico)}</td><td>{moeda(s.comissaoServico)}</td></tr>)}</tbody></table></div>{!comissao.servicos.length?<p className="empty-inline">Nenhum serviço pago neste período. A comissão está aguardando OP.</p>:null}</article>
      <article className="panel food-panel"><header className="panel-title"><div><span className="eyebrow">Uso diário</span><h2>Alimentação</h2></div></header><form className="form-grid" onSubmit={salvar}><label className="field"><span>Data da alimentação</span><input aria-label="Data da alimentação" name="data" type="date" required/></label><label className="field"><span>Valor da alimentação</span><input aria-label="Valor da alimentação" name="valor" type="number" min=".01" step=".01" required/></label><label className="field field-wide"><span>Observação</span><input name="observacoes" placeholder="Opcional"/></label><button className="button button-primary" disabled={salvando}>Registrar alimentação</button></form><div className="food-list">{comissao.alimentacoes.map(a=><div key={a.id}><span><strong>{data(a.data)}</strong><small>{a.aprovada?'Aprovada':a.situacao.toLowerCase()}</small></span><strong>{moeda(a.valor)}</strong></div>)}</div></article></section></>:null}
  </div>
}
