import { useEffect, useState } from 'react'
import { avaliarImportacaoPorto, cancelarImportacaoPorto, confirmarImportacaoPorto, criarPreviaConteudoPorto, criarPreviaPorto, listarCalendarioPorto, listarOrdensPagamentoPorto } from '../api/porto'
import type { CalendarioPorto, OrdemPagamentoPorto, PreviaPorto } from '../types/modelos'
import { moeda } from '../utils/formatadores'

const rotulos={PREVISAO_RECEBER:'Previsão a receber',OS_VINCULADAS:'OS vinculadas à OP',SERVICOS_DEVOLVIDOS:'Serviços devolvidos',SERVICOS_GERAIS:'Serviços gerais da Porto',SERVICOS_AGUARDANDO_LANCAMENTO:'Serviços aguardando lançamento'}
const dataBr=(valor?:string)=>valor?new Date(`${valor}T12:00:00`).toLocaleDateString('pt-BR'):''

export default function PortoImportacoesPage(){
  const [arquivo,setArquivo]=useState<File|null>(null),[previa,setPrevia]=useState<PreviaPorto|null>(null)
  const [modo,setModo]=useState<'arquivo'|'colagem'>('arquivo'),[conteudo,setConteudo]=useState('')
  const [ops,setOps]=useState<OrdemPagamentoPorto[]>([]),[periodos,setPeriodos]=useState<CalendarioPorto[]>([]),[opId,setOpId]=useState(''),[periodoId,setPeriodoId]=useState(''),[mensagem,setMensagem]=useState(''),[erro,setErro]=useState(''),[carregando,setCarregando]=useState(false)
  const [confirmarDivergencias,setConfirmarDivergencias]=useState(false),[inputKey,setInputKey]=useState(0)
  useEffect(()=>{Promise.all([listarOrdensPagamentoPorto(),listarCalendarioPorto()]).then(([o,p])=>{setOps(o);setPeriodos(p)}).catch(e=>setErro(e.message))},[])
  async function analisar(){if(modo==='arquivo'&&!arquivo||modo==='colagem'&&!conteudo.trim())return;setCarregando(true);setErro('');setOpId('');setPeriodoId('');setConfirmarDivergencias(false);try{setPrevia(modo==='arquivo'?await criarPreviaPorto(arquivo as File):await criarPreviaConteudoPorto(conteudo))}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  async function selecionarOp(valor:string){setOpId(valor);const selecionada=ops.find(op=>op.id===Number(valor));setPeriodoId(selecionada?.calendarioPagamentoId?String(selecionada.calendarioPagamentoId):'');setConfirmarDivergencias(false);if(!previa||!valor)return;setCarregando(true);setErro('');try{setPrevia(await avaliarImportacaoPorto(previa.id,Number(valor)))}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  async function confirmar(){if(!previa||previa.requerOrdemPagamento&&(!opId||!periodoId))return;setCarregando(true);setErro('');try{const r=await confirmarImportacaoPorto(previa.id,opId?Number(opId):undefined,confirmarDivergencias,undefined,undefined,periodoId?Number(periodoId):undefined);const financeiro=r.tipo==='OS_VINCULADAS'||r.tipo==='SERVICOS_GERAIS'?` · ${r.receitasCriadas} ${r.receitasCriadas===1?'receita criada':'receitas criadas'} · ${r.receitasAtualizadas} ${r.receitasAtualizadas===1?'receita atualizada':'receitas atualizadas'} · ${moeda(r.valorTotalRecebido)} recebidos${r.quinzena?` · período ${r.quinzena}`:''}${r.dataPagamento?` · pagamento em ${dataBr(r.dataPagamento)}`:''}`:'';setMensagem(`${r.importados} ${r.importados===1?'registro importado':'registros importados'}${r.ignorados?` · ${r.ignorados} ignorados por duplicidade`:''}${financeiro}.`);setPrevia(null);setArquivo(null);setOps(await listarOrdensPagamentoPorto());setInputKey(x=>x+1)}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  async function cancelar(){if(!previa)return;setCarregando(true);setErro('');try{await cancelarImportacaoPorto(previa.id);setMensagem('Prévia cancelada. Corrija e reenvie o arquivo quando estiver pronto.');setPrevia(null);setArquivo(null);setOpId('');setInputKey(x=>x+1)}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  function limpar(){setConteudo('');setArquivo(null);setPrevia(null);setErro('');setMensagem('');setInputKey(x=>x+1)}
  const temErros=Boolean(previa?.erros.length||previa?.linhas.some(l=>l.acao==='ERRO'))
  const temDivergencias=Boolean(previa?.linhas.some(l=>l.acao==='DIVERGENCIA'))
  return <div className="page-enter"><header className="page-heading"><div><span className="eyebrow">Módulo Porto</span><h1>Importar relatórios</h1><p>Cole serviços ou envie CSV/TXT, confira a prévia e confirme somente depois da validação.</p></div></header>
    {erro?<div className="form-alert">{erro}</div>:null}{mensagem?<div className="success-notice">{mensagem}</div>:null}
    <section className="panel porto-import-card"><div className="segmented porto-import-modes" role="group" aria-label="Forma de importação"><button className={modo==='arquivo'?'active':''} onClick={()=>{setModo('arquivo');setPrevia(null)}}>Enviar arquivo</button><button className={modo==='colagem'?'active':''} onClick={()=>{setModo('colagem');setPrevia(null)}}>Colar serviços da Porto</button></div>
      {modo==='arquivo'?<div className="porto-upload"><label className="field"><span>Arquivo CSV ou TXT</span><input key={inputKey} aria-label="Arquivo CSV" type="file" accept=".csv,.txt,text/csv,text/plain" onChange={e=>{setArquivo(e.target.files?.[0]??null);setPrevia(null);setMensagem('')}}/></label>
      <button className="button button-primary" disabled={!arquivo||carregando} onClick={analisar}>{carregando?'Analisando…':'Analisar CSV'}</button></div>:<div className="porto-paste"><label className="field"><span>Conteúdo copiado da Porto</span><textarea aria-label="Conteúdo copiado da Porto" rows={10} value={conteudo} onChange={e=>{setConteudo(e.target.value);setPrevia(null);setMensagem('')}} placeholder="Cole aqui a tabela copiada com Ctrl+C"/></label><div className="porto-paste-actions"><button className="button button-ghost" type="button" onClick={limpar}>Limpar</button><button className="button button-primary" disabled={!conteudo.trim()||carregando} onClick={analisar}>{carregando?'Analisando…':'Analisar conteúdo'}</button></div></div>}
      {previa?<div className="porto-preview"><header className="panel-title"><div><span className="eyebrow">Prévia detectada</span><h2>{rotulos[previa.tipo]}</h2></div><span className="import-pill">{previa.totalLinhas} linhas</span></header>
        {previa.resumo?<div className="porto-preview-summary"><span><strong>{previa.resumo.linhasAnalisadas}</strong> linhas analisadas</span>{previa.tipo==='PREVISAO_RECEBER'?<span><strong>{previa.resumo.opsUnicas}</strong> OPs únicas</span>:null}<span><strong>{previa.resumo.registrosNovos}</strong> registros novos</span><span><strong>{previa.resumo.registrosExistentes}</strong> já existentes</span>{previa.tipo==='PREVISAO_RECEBER'?<span><strong>{previa.resumo.registrosAtualizados}</strong> {previa.resumo.registrosAtualizados===1?'registro atualizado':'registros atualizados'}</span>:null}<span><strong>{previa.resumo.duplicidades}</strong> duplicidades</span><span><strong>{previa.resumo.erros}</strong> erros</span><span><strong>{moeda(previa.resumo.valorTotal)}</strong> valor total</span></div>:null}
        {temErros?<div className="form-alert"><strong>Corrija e reenvie o arquivo.</strong> {previa.erros.join(' · ')}</div>:null}
        <footer className="porto-confirm porto-confirm-sticky" aria-label="Ações da prévia"><div className="porto-confirm-totals"><span><strong>{previa.totalLinhas}</strong> registros</span><span><strong>{moeda(previa.resumo?.valorTotal??0)}</strong> valor total</span></div>{previa.requerOrdemPagamento?<label className="field"><span>Ordem de pagamento</span><select aria-label="Ordem de pagamento" value={opId} onChange={e=>void selecionarOp(e.target.value)} required><option value="">Selecione a OP</option>{ops.map(op=><option key={op.id} value={op.id}>{op.numero}</option>)}</select></label>:null}
          {previa.requerOrdemPagamento?<label className="field"><span>Período financeiro</span><select aria-label="Período financeiro" value={periodoId} onChange={e=>setPeriodoId(e.target.value)} required><option value="">Selecione o período</option>{periodos.filter(p=>p.ativo||String(p.id)===periodoId).map(p=><option key={p.id} value={p.id}>{p.descricao} · {dataBr(p.competenciaInicio)} a {dataBr(p.competenciaFim)}</option>)}</select></label>:null}
          {temDivergencias?<label className="porto-divergence"><input type="checkbox" aria-label="Confirmo a reassociação" checked={confirmarDivergencias} onChange={e=>setConfirmarDivergencias(e.target.checked)}/><span>Confirmo a reassociação das OS indicadas.</span></label>:null}
          <button type="button" className="button button-ghost" disabled={carregando} onClick={cancelar}>Cancelar prévia</button>
          <button className="button button-primary" disabled={carregando||temErros||temDivergencias&&!confirmarDivergencias||previa.requerOrdemPagamento&&(!opId||!periodoId)||previa.linhas.length===0} onClick={confirmar}>Confirmar importação</button></footer>
        <div className="table-scroll porto-preview-table"><table><thead><tr><th>Ordem</th><th>Especialidade / Nome</th><th>Valor</th><th>Data</th><th>Ação</th></tr></thead><tbody>{previa.linhas.map(l=><tr key={l.hashRegistro}><td><strong>{l.dados.numero_op||l.dados.numero_os}</strong></td><td>{l.dados.especialidade||l.dados.nome_codigo||'—'}</td><td>{l.dados.valor_total}</td><td>{l.dados.data_pagamento||l.dados.data_atendimento}</td><td>{l.mensagem||l.acao}</td></tr>)}</tbody></table></div></div>:null}
    </section></div>
}
