import { useEffect, useState, type FormEvent } from 'react'
import { baixarRelatorioPorto, obterDashboardPorto } from '../api/porto'
import type { DashboardPorto } from '../types/modelos'
import { moeda } from '../utils/formatadores'

export default function PortoDashboardPage(){
  const [dados,setDados]=useState<DashboardPorto|null>(null),[erro,setErro]=useState(''),[parametros,setParametros]=useState(new URLSearchParams())
  const [visao,setVisao]=useState<'PRODUCAO'|'PAGAMENTOS'>('PRODUCAO'),[periodo,setPeriodo]=useState('MENSAL')
  async function carregar(params:URLSearchParams){setErro('');try{setDados(await obterDashboardPorto(params));setParametros(new URLSearchParams(params))}catch(e){setErro((e as Error).message)}}
  useEffect(()=>{const params=new URLSearchParams({periodo:'MENSAL',visao:'PRODUCAO',referencia:new Date().toISOString().slice(0,10)});void carregar(params)},[])
  async function trocarVisao(nova:'PRODUCAO'|'PAGAMENTOS'){setVisao(nova);const params=new URLSearchParams(parametros);params.set('visao',nova);params.set('periodo',periodo);await carregar(params)}
  async function aplicar(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),params=new URLSearchParams({periodo,visao});for(const nome of ['referencia','dataInicio','dataFim','numeroOs','numeroOp','especialidade','socorrista','statusOperacional','statusFinanceiro','statusConciliacao']){const valor=String(form.get(nome)??'');if(valor)params.set(nome,valor)}await carregar(params)}
  async function exportar(formato:'excel'|'pdf'){try{await baixarRelatorioPorto(formato,parametros)}catch(e){setErro((e as Error).message)}}
  return <div className="page-enter"><header className="page-heading"><div><span className="eyebrow">Porto Seguro</span><h1>Dashboard Porto</h1><p>Serviços realizados, pagamentos programados e valores efetivamente recebidos.</p></div><div className="heading-actions"><button className="button button-ghost" onClick={()=>void exportar('pdf')}>Exportar PDF</button><button className="button button-primary" onClick={()=>void exportar('excel')}>Exportar Excel</button></div></header>{erro?<div className="form-alert">{erro}</div>:null}
    <section className="panel"><div className="porto-view-switch" role="group" aria-label="Linha do tempo Porto"><button className={visao==='PRODUCAO'?'active':''} onClick={()=>void trocarVisao('PRODUCAO')}>Produção</button><button className={visao==='PAGAMENTOS'?'active':''} onClick={()=>void trocarVisao('PAGAMENTOS')}>Pagamentos</button></div><form className="ledger-filters porto-dashboard-filters" onSubmit={aplicar}><label><span>Período</span><select aria-label="Período" value={periodo} onChange={e=>setPeriodo(e.target.value)}><option value="DIARIO">Dia</option><option value="SEMANAL">Semana</option><option value="QUINZENAL">Quinzena</option><option value="MENSAL">Mês</option><option value="PERSONALIZADO">Personalizado</option></select></label><label><span>Referência</span><input name="referencia" type="date" defaultValue={new Date().toISOString().slice(0,10)}/></label>{periodo==='PERSONALIZADO'?<><label><span>Data inicial</span><input name="dataInicio" type="date" required/></label><label><span>Data final</span><input name="dataFim" type="date" required/></label></>:null}<label className="filter-grow"><span>Número da OS</span><input aria-label="Número da OS" name="numeroOs"/></label><label><span>Número da OP</span><input name="numeroOp"/></label><label><span>Especialidade</span><input name="especialidade"/></label><label><span>Socorrista</span><input name="socorrista"/></label><button className="button button-primary">Aplicar filtros</button></form></section>
    {dados?<><section className="porto-finance-lane"><article><span>Realizado</span><strong>{moeda(dados.valorTotalRealizado)}</strong><small>{dados.quantidadeTotalServicos} serviços executados</small></article><article><span>Programado</span><strong>{moeda(dados.valorProgramado)}</strong><small>{dados.quantidadePagamentoProgramado} ordens de pagamento</small></article><article><span>Recebido</span><strong>{moeda(dados.valorRecebido)}</strong><small>{dados.quantidadeRecebidas} recebimentos confirmados</small></article></section>
      <section className="metric-grid porto-dashboard-metrics"><article className="metric"><span>Serviços realizados</span><strong>{dados.quantidadeTotalServicos}</strong></article><article className="metric"><span>Aguardando OP</span><strong>{dados.quantidadeAguardandoOp}</strong><small>{moeda(dados.valorAguardandoOp)}</small></article><article className="metric"><span>OPs com divergência</span><strong>{dados.quantidadeComDivergencia}</strong><small>{moeda(dados.valorTotalDivergencias)}</small></article><article className="metric"><span>Serviços pendentes</span><strong>{dados.quantidadeServicosPendentes}</strong><small>{moeda(dados.valorServicosPendentes)}</small></article><article className="metric"><span>Serviços devolvidos</span><strong>{dados.quantidadeServicosDevolvidos}</strong></article><article className="metric"><span>OPs vencidas</span><strong>{dados.quantidadeVencidasNaoRecebidas}</strong><small>{moeda(dados.valorVencidoNaoRecebido)}</small></article></section>
      <section className="porto-breakdowns"><article className="panel"><header className="panel-title"><h2>Por especialidade</h2></header><div className="table-scroll"><table><thead><tr><th>Especialidade</th><th>Quantidade</th><th>Valor</th></tr></thead><tbody>{dados.porEspecialidade.map(x=><tr key={x.chave}><td>{x.chave}</td><td>{x.quantidade}</td><td>{moeda(x.valor)}</td></tr>)}</tbody></table></div></article><article className="panel"><header className="panel-title"><h2>Por socorrista</h2></header><div className="table-scroll"><table><thead><tr><th>Socorrista</th><th>Quantidade</th><th>Valor</th></tr></thead><tbody>{dados.porSocorrista.map(x=><tr key={x.chave}><td>{x.chave}</td><td>{x.quantidade}</td><td>{moeda(x.valor)}</td></tr>)}</tbody></table></div></article></section></>:null}
  </div>
}
