import { useEffect, useState, type FormEvent } from 'react'
import { associarMotoristaPorto,listarOrdensServicoPorto } from '../api/porto'
import { api } from '../api/http'
import { Vazio } from '../components/EstadoPagina'
import type { Motorista,OrdemServicoPorto } from '../types/modelos'
import { moeda } from '../utils/formatadores'

const rotulo=(valor?:string)=>valor?valor.toLowerCase().replaceAll('_',' ').replace(/^./,x=>x.toUpperCase()):'—'
export default function PortoOrdensServicoPage(){
  const [itens,setItens]=useState<OrdemServicoPorto[]>([]),[motoristas,setMotoristas]=useState<Motorista[]>([]),[associando,setAssociando]=useState<OrdemServicoPorto|null>(null),[motoristaId,setMotoristaId]=useState(0),[somenteNaoIdentificados,setSomenteNaoIdentificados]=useState(false),[erro,setErro]=useState('')
  async function carregar(params=new URLSearchParams()){setErro('');try{setItens(await listarOrdensServicoPorto(params))}catch(e){setErro((e as Error).message)}}
  useEffect(()=>{void carregar();api<Motorista[]>('/api/motoristas').then(setMotoristas).catch(e=>setErro(e.message))},[])
  async function aplicar(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),params=new URLSearchParams();for(const nome of ['numeroOs','numeroOp','especialidade','socorrista','qra','viatura','statusOperacional','statusFinanceiro']){const valor=String(form.get(nome)??'');if(valor)params.set(nome,valor)}await carregar(params)}
  async function confirmarAssociacao(){if(!associando||!motoristaId)return;try{const atualizada=await associarMotoristaPorto(associando.id,motoristaId);setItens(lista=>lista.map(os=>os.id===atualizada.id?atualizada:os));setAssociando(null);setMotoristaId(0)}catch(e){setErro((e as Error).message)}}
  const visiveis=somenteNaoIdentificados?itens.filter(os=>!os.motoristaId):itens
  return <div className="page-enter"><header className="page-heading"><div><span className="eyebrow">Porto Seguro</span><h1>Ordens de serviço</h1><p>Serviços individuais importados, com previsão original e ciclo efetivo.</p></div></header>{erro?<div className="form-alert">{erro}</div>:null}<section className="panel"><form className="ledger-filters porto-os-filters" onSubmit={aplicar}><label className="filter-grow"><span>Número da OS</span><input name="numeroOs"/></label><label><span>Número da OP</span><input name="numeroOp"/></label><label><span>Especialidade</span><input aria-label="Especialidade" name="especialidade"/></label><label><span>Socorrista</span><input name="socorrista"/></label><label><span>Status operacional</span><select name="statusOperacional"><option value="">Todos</option><option value="AGUARDANDO_LANCAMENTO">Aguardando lançamento</option><option value="PROCESSADO">Processado</option><option value="LIBERADO_APOS_ANALISE">Liberado após análise</option><option value="NORMAL">Normal</option><option value="PENDENTE_PORTO">Pendente Porto</option><option value="DEVOLVIDO_FINALIZADO">Devolvido finalizado</option></select></label><label><span>Status financeiro</span><select name="statusFinanceiro"><option value="">Todos</option><option value="AGUARDANDO_OP">Aguardando OP</option><option value="PAGAMENTO_PROGRAMADO">Pagamento programado</option><option value="A_CONFIRMAR">A confirmar</option><option value="RECEBIDO">Recebido</option><option value="BLOQUEADO_PARA_PAGAMENTO">Bloqueado</option><option value="VALOR_DIVERGENTE">Valor divergente</option></select></label><button className="button button-primary">Aplicar filtros</button></form>
    <label className="check-field"><input type="checkbox" checked={somenteNaoIdentificados} onChange={e=>setSomenteNaoIdentificados(e.target.checked)}/> Somente funcionários não identificados</label>
    {visiveis.length?<div className="table-scroll"><table><thead><tr><th>OS</th><th>OP</th><th>Especialidade</th><th>Viatura</th><th>Socorrista / QRA</th><th>Funcionário</th><th>Atendimento</th><th>Previsão original</th><th>Ciclo efetivo</th><th>Valor</th><th>Operacional</th><th>Financeiro</th></tr></thead><tbody>{visiveis.map(os=><tr key={os.id}><td><strong>{os.numero}</strong></td><td>{os.ordemPagamento||'—'}</td><td>{os.especialidade||'—'}</td><td>{os.viatura||'Sem viatura'}</td><td><strong>{os.socorrista||'—'}</strong><small>{os.qra||'Sem QRA'}</small></td><td>{os.motorista?<><strong>{os.motorista}</strong><button className="table-action" onClick={()=>{setAssociando(os);setMotoristaId(os.motoristaId??0)}}>Alterar</button></>:<button className="table-action table-action-danger" onClick={()=>setAssociando(os)}>Associar funcionário</button>}</td><td>{os.dataAtendimento?new Date(`${os.dataAtendimento}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td>{os.dataPrevistaOriginal?new Date(`${os.dataPrevistaOriginal}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td>{os.dataEfetivaPagamento?new Date(`${os.dataEfetivaPagamento}T12:00:00`).toLocaleDateString('pt-BR'):'—'}{os.ciclosAtraso?<small>{os.ciclosAtraso} ciclo(s) depois</small>:null}</td><td>{moeda(os.valorTotal)}</td><td>{rotulo(os.statusOperacional)}</td><td>{rotulo(os.statusFinanceiro)}</td></tr>)}</tbody></table></div>:<Vazio titulo="Nenhuma OS" descricao="Cole serviços da Porto ou ajuste os filtros."/>}</section>
    {associando?<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label={`Associar funcionário à ${associando.numero}`}><header><div><span className="eyebrow">{associando.numero}</span><h2>Associar funcionário</h2></div><button aria-label="Fechar" onClick={()=>setAssociando(null)}>×</button></header><p>Confirme o motorista responsável. A associação manual será preservada em futuras reimportações.</p><label className="field"><span>Funcionário</span><select aria-label="Funcionário responsável" value={motoristaId||''} onChange={e=>setMotoristaId(Number(e.target.value))} required><option value="">Selecione</option>{motoristas.filter(m=>m.ativo).map(m=><option key={m.id} value={m.id}>{m.nome}{m.qra?` · ${m.qra}`:''}</option>)}</select></label><div className="modal-actions"><button className="button button-ghost" onClick={()=>setAssociando(null)}>Cancelar</button><button className="button button-primary" disabled={!motoristaId} onClick={()=>void confirmarAssociacao()}>Confirmar associação</button></div></section></div>:null}
  </div>
}
