import { useEffect,useState,type FormEvent } from 'react'
import { atualizarDataCalendarioPorto,criarDataCalendarioPorto,desativarDataCalendarioPorto,listarCalendarioPorto } from '../api/porto'
import type { CalendarioPorto } from '../types/modelos'

const data=(valor:string)=>new Date(`${valor}T12:00:00`).toLocaleDateString('pt-BR')
export default function PortoCalendarioPage(){
  const [itens,setItens]=useState<CalendarioPorto[]>([]),[editando,setEditando]=useState<CalendarioPorto|null>(null)
  const [erro,setErro]=useState(''),[carregando,setCarregando]=useState(false)
  async function carregar(){try{setItens(await listarCalendarioPorto())}catch(e){setErro((e as Error).message)}}
  useEffect(()=>{void carregar()},[])
  async function adicionar(event:FormEvent<HTMLFormElement>){event.preventDefault();setCarregando(true);setErro('');const elemento=event.currentTarget,form=new FormData(elemento);try{await criarDataCalendarioPorto({dataPagamento:String(form.get('data')),competenciaInicio:String(form.get('competenciaInicio')),competenciaFim:String(form.get('competenciaFim')),descricao:String(form.get('descricao')),ativo:true});elemento.reset();await carregar()}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  async function salvarEdicao(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!editando)return;setCarregando(true);setErro('');const form=new FormData(event.currentTarget);try{await atualizarDataCalendarioPorto(editando.id,{dataPagamento:String(form.get('data')),competenciaInicio:String(form.get('competenciaInicio')),competenciaFim:String(form.get('competenciaFim')),descricao:String(form.get('descricao')),ativo:editando.ativo});setEditando(null);await carregar()}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  async function desativar(id:number){setCarregando(true);try{await desativarDataCalendarioPorto(id);await carregar()}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  return <div className="page-enter"><header className="page-heading"><div><span className="eyebrow">Porto Seguro</span><h1>Calendário de pagamentos</h1><p>Datas configuráveis usadas para prever o próximo ciclo dos serviços.</p></div></header>{erro?<div className="form-alert">{erro}</div>:null}
    <section className="panel"><form className="ledger-filters" onSubmit={adicionar}><label><span>Início da competência</span><input aria-label="Início da competência" name="competenciaInicio" type="date" required/></label><label><span>Fim da competência</span><input aria-label="Fim da competência" name="competenciaFim" type="date" required/></label><label><span>Data de pagamento</span><input aria-label="Data de pagamento" name="data" type="date" required/></label><label className="filter-grow"><span>Descrição</span><input aria-label="Descrição" name="descricao" required/></label><button className="button button-primary" disabled={carregando}>Adicionar data</button></form>
      <div className="table-scroll"><table><thead><tr><th>Competência</th><th>Pagamento</th><th>Descrição</th><th>Situação</th><th/></tr></thead><tbody>{itens.map(item=><tr key={item.id}><td>{item.competenciaInicio&&item.competenciaFim?`${data(item.competenciaInicio)} a ${data(item.competenciaFim)}`:'Não configurada'}</td><td><strong>{data(item.dataPagamento)}</strong></td><td>{item.descricao}</td><td>{item.ativo?'Ativa':'Inativa'}</td><td><div className="heading-actions"><button className="table-action" disabled={carregando} onClick={()=>setEditando(item)}>Editar {item.descricao}</button>{item.ativo?<button className="table-action" disabled={carregando} onClick={()=>void desativar(item.id)}>Desativar</button>:null}</div></td></tr>)}</tbody></table></div>
    </section>
    {editando?<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Calendário Porto</span><h2>Editar data de pagamento</h2></div><button aria-label="Fechar edição" onClick={()=>setEditando(null)}>×</button></header><form className="form-grid" onSubmit={salvarEdicao}><label className="field"><span>Início da competência</span><input name="competenciaInicio" type="date" defaultValue={editando.competenciaInicio} required/></label><label className="field"><span>Fim da competência</span><input name="competenciaFim" type="date" defaultValue={editando.competenciaFim} required/></label><label className="field"><span>Data de pagamento</span><input name="data" type="date" defaultValue={editando.dataPagamento} required/></label><label className="field"><span>Descrição</span><input name="descricao" defaultValue={editando.descricao} required/></label><div className="modal-actions"><button type="button" className="button button-ghost" onClick={()=>setEditando(null)}>Cancelar</button><button className="button button-primary" disabled={carregando}>Salvar alterações</button></div></form></section></div>:null}
  </div>
}
