import { useEffect, useState, type FormEvent } from 'react'
import { listarOrdensServicoPorto } from '../api/porto'
import { Vazio } from '../components/EstadoPagina'
import type { OrdemServicoPorto } from '../types/modelos'
import { moeda } from '../utils/formatadores'

const rotulo=(valor?:string)=>valor?valor.toLowerCase().replaceAll('_',' ').replace(/^./,x=>x.toUpperCase()):'—'
export default function PortoOrdensServicoPage(){
  const [itens,setItens]=useState<OrdemServicoPorto[]>([]),[erro,setErro]=useState('')
  async function carregar(params=new URLSearchParams()){setErro('');try{setItens(await listarOrdensServicoPorto(params))}catch(e){setErro((e as Error).message)}}
  useEffect(()=>{void carregar()},[])
  async function aplicar(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),params=new URLSearchParams();for(const nome of ['numeroOs','numeroOp','especialidade','socorrista','qra','viatura','statusOperacional','statusFinanceiro']){const valor=String(form.get(nome)??'');if(valor)params.set(nome,valor)}await carregar(params)}
  return <div className="page-enter"><header className="page-heading"><div><span className="eyebrow">Porto Seguro</span><h1>Ordens de serviço</h1><p>Serviços individuais importados, com ou sem ordem de pagamento.</p></div></header>{erro?<div className="form-alert">{erro}</div>:null}<section className="panel"><form className="ledger-filters porto-os-filters" onSubmit={aplicar}><label className="filter-grow"><span>Número da OS</span><input name="numeroOs"/></label><label><span>Número da OP</span><input name="numeroOp"/></label><label><span>Especialidade</span><input aria-label="Especialidade" name="especialidade"/></label><label><span>Socorrista</span><input name="socorrista"/></label><label><span>Status operacional</span><select name="statusOperacional"><option value="">Todos</option><option value="NORMAL">Normal</option><option value="PENDENTE_PORTO">Pendente Porto</option><option value="DEVOLVIDO_FINALIZADO">Devolvido finalizado</option></select></label><label><span>Status financeiro</span><select name="statusFinanceiro"><option value="">Todos</option><option value="AGUARDANDO_OP">Aguardando OP</option><option value="PAGAMENTO_PROGRAMADO">Pagamento programado</option><option value="RECEBIDO">Recebido</option><option value="BLOQUEADO_PARA_PAGAMENTO">Bloqueado</option><option value="VALOR_DIVERGENTE">Valor divergente</option></select></label><button className="button button-primary">Aplicar filtros</button></form>
    {itens.length?<div className="table-scroll"><table><thead><tr><th>OS</th><th>OP</th><th>Especialidade</th><th>Viatura</th><th>Socorrista / QRA</th><th>Atendimento</th><th>Valor</th><th>Operacional</th><th>Financeiro</th></tr></thead><tbody>{itens.map(os=><tr key={os.id}><td><strong>{os.numero}</strong></td><td>{os.ordemPagamento||'—'}</td><td>{os.especialidade||'—'}</td><td>{os.viatura||'Sem viatura'}</td><td><strong>{os.socorrista||'—'}</strong><small>{os.qra||'Sem QRA'}</small></td><td>{os.dataAtendimento?new Date(`${os.dataAtendimento}T12:00:00`).toLocaleDateString('pt-BR'):'—'}</td><td>{moeda(os.valorTotal)}</td><td>{rotulo(os.statusOperacional)}</td><td>{rotulo(os.statusFinanceiro)}</td></tr>)}</tbody></table></div>:<Vazio titulo="Nenhuma OS" descricao="Cole serviços da Porto ou ajuste os filtros."/>}</section></div>
}
