import { useEffect, useState, type FormEvent } from 'react'
import { baixarRelatorioPorto, detalharOrdemPagamentoPorto, justificarOrdemPagamentoPorto, listarOrdensPagamentoPorto, receberOrdemPagamentoPorto, resumirOrdensPagamentoPorto } from '../api/porto'
import { Vazio } from '../components/EstadoPagina'
import type { DetalheOpPorto, OrdemPagamentoPorto, ResumoOpsPorto } from '../types/modelos'
import { moeda } from '../utils/formatadores'

const data=(valor?:string)=>valor?new Date(`${valor}T12:00:00`).toLocaleDateString('pt-BR'):'—'
const vazio:ResumoOpsPorto={quantidadeTotalOps:0,valorTotalPrevisto:0,quantidadeSemComposicao:0,valorSemComposicao:0,quantidadeConciliadas:0,valorConciliadas:0,quantidadeValorAbaixo:0,diferencaTotalAbaixo:0,quantidadeValorAcima:0,diferencaTotalAcima:0,quantidadeComDivergencia:0,valorTotalDivergencias:0,quantidadePagamentoProgramado:0,valorProgramado:0,quantidadeRecebidas:0,valorRecebido:0,quantidadeAguardandoRecebimento:0,valorAguardandoRecebimento:0,quantidadeVencidasNaoRecebidas:0,valorVencidoNaoRecebido:0,valorMedioPorOp:0,quantidadeOrdensServico:0}
const rotulo=(valor?:string)=>valor?valor.toLowerCase().replaceAll('_',' ').replace(/^./,x=>x.toUpperCase()):'—'

export default function PortoOrdensPagamentoPage(){
  const [itens,setItens]=useState<OrdemPagamentoPorto[]>([]),[resumo,setResumo]=useState<ResumoOpsPorto>(vazio)
  const [recebimento,setRecebimento]=useState<OrdemPagamentoPorto|null>(null),[detalhe,setDetalhe]=useState<DetalheOpPorto|null>(null)
  const [erro,setErro]=useState(''),[carregando,setCarregando]=useState(false),[parametros,setParametros]=useState(new URLSearchParams())
  async function carregar(params:URLSearchParams){setCarregando(true);setErro('');try{const [lista,total]=await Promise.all([listarOrdensPagamentoPorto(params),resumirOrdensPagamentoPorto(params)]);setItens(lista);setResumo(total);setParametros(new URLSearchParams(params))}catch(e){setErro((e as Error).message)}finally{setCarregando(false)}}
  useEffect(()=>{void carregar(new URLSearchParams())},[])
  async function aplicar(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget),p=new URLSearchParams();for(const chave of ['numero','dataInicio','dataFim','situacaoPagamento','statusConciliacao','recebida','vencida','comComposicao','comDivergencia']){const valor=String(f.get(chave)??'');if(valor)p.set(chave,valor)}await carregar(p)}
  async function receber(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!recebimento)return;const f=new FormData(event.currentTarget);try{await receberOrdemPagamentoPorto(recebimento.id,Number(f.get('valor')),String(f.get('data')));setRecebimento(null);await carregar(parametros)}catch(e){setErro((e as Error).message)}}
  async function abrirDetalhe(id:number){setErro('');try{setDetalhe(await detalharOrdemPagamentoPorto(id))}catch(e){setErro((e as Error).message)}}
  async function justificar(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!detalhe)return;const f=new FormData(event.currentTarget);try{await justificarOrdemPagamentoPorto(detalhe.ordemPagamento.id,String(f.get('motivo')),String(f.get('observacao')));setDetalhe(await detalharOrdemPagamentoPorto(detalhe.ordemPagamento.id));event.currentTarget.reset()}catch(e){setErro((e as Error).message)}}
  async function exportar(formato:'excel'|'pdf'){setErro('');try{await baixarRelatorioPorto(formato,parametros)}catch(e){setErro((e as Error).message)}}
  const cards=[['Total de OPs',String(resumo.quantidadeTotalOps)],['Valor total previsto',moeda(resumo.valorTotalPrevisto)],['OPs conciliadas',String(resumo.quantidadeConciliadas)],['OPs com divergência',String(resumo.quantidadeComDivergencia)],['OPs recebidas',String(resumo.quantidadeRecebidas)],['OPs aguardando recebimento',String(resumo.quantidadeAguardandoRecebimento)],['OPs vencidas',String(resumo.quantidadeVencidasNaoRecebidas)],['Valor médio por OP',moeda(resumo.valorMedioPorOp)]]
  return <div className="page-enter"><header className="page-heading"><div><span className="eyebrow">Porto Seguro</span><h1>Ordens de pagamento</h1><p>Conciliação por OP, programações e recebimentos confirmados manualmente.</p></div><div className="heading-actions"><button className="button button-ghost" onClick={()=>void exportar('pdf')}>Exportar PDF</button><button className="button button-primary" onClick={()=>void exportar('excel')}>Exportar Excel</button></div></header>{erro?<div className="form-alert">{erro}</div>:null}
    <section className="metric-grid porto-op-metrics">{cards.map(([nome,valor])=><article className="metric" key={nome}><span>{nome}</span><strong>{valor}</strong></article>)}</section>
    <section className="panel"><form className="ledger-filters porto-op-filters" onSubmit={aplicar}><label className="filter-grow"><span>Número da OP</span><input aria-label="Número da OP" name="numero"/></label><label><span>Data inicial</span><input name="dataInicio" type="date"/></label><label><span>Data final</span><input name="dataFim" type="date"/></label><label><span>Recebimento</span><select name="recebida"><option value="">Todos</option><option value="true">Recebidas</option><option value="false">Não recebidas</option></select></label><label><span>Conciliação</span><select name="statusConciliacao"><option value="">Todas</option><option value="SEM_COMPOSICAO">Sem composição</option><option value="CONCILIADA">Conciliada</option><option value="VALOR_ABAIXO">Valor abaixo</option><option value="VALOR_ACIMA">Valor acima</option><option value="RECEBIDA_COM_DIVERGENCIA">Recebida com divergência</option></select></label><button className="button button-primary" disabled={carregando}>Aplicar filtros</button></form>
      {itens.length?<div className="table-scroll"><table><thead><tr><th>Número da OP</th><th>Data programada</th><th>OS vinculadas</th><th>Valor previsto</th><th>Soma das OS</th><th>Diferença</th><th>Conciliação</th><th>Recebimento</th><th>Valor recebido</th><th>Data recebida</th><th/></tr></thead><tbody>{itens.map(op=><tr key={op.id}><td><button className="table-action" onClick={()=>void abrirDetalhe(op.id)}><strong>{op.numero}</strong></button></td><td>{data(op.dataPagamentoProgramada)}</td><td>{op.quantidadeOrdensServico??0}</td><td>{moeda(op.valorTotal)}</td><td>{moeda(op.valorOrdensServico??0)}</td><td>{moeda(op.divergencia??0)}</td><td><span className="ledger-status ledger-pendente">{rotulo(op.statusConciliacao)}</span></td><td>{op.situacao==='RECEBIDO'?'Recebido':'Programado'}</td><td>{op.valorRecebido==null?'—':moeda(op.valorRecebido)}</td><td>{data(op.dataRecebimento)}</td><td>{op.situacao!=='RECEBIDO'?<button className="table-action" onClick={()=>setRecebimento(op)}>Confirmar recebimento</button>:null}</td></tr>)}</tbody></table></div>:<Vazio titulo="Nenhuma OP" descricao="Importe a Previsão a Receber ou ajuste os filtros."/>}</section>
    {recebimento?<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true"><header><div><span className="eyebrow">{recebimento.numero}</span><h2>Confirmar recebimento</h2></div><button aria-label="Fechar" onClick={()=>setRecebimento(null)}>×</button></header><form className="form-grid" onSubmit={receber}><label className="field"><span>Valor recebido</span><input aria-label="Valor recebido" name="valor" type="number" step=".01" min=".01" defaultValue={recebimento.valorTotal} required/></label><label className="field"><span>Data do recebimento</span><input name="data" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><div className="modal-actions"><button type="button" className="button button-ghost" onClick={()=>setRecebimento(null)}>Cancelar</button><button className="button button-primary">Salvar recebimento</button></div></form></section></div>:null}
    {detalhe?<div className="modal-backdrop"><section className="modal porto-op-detail" role="dialog" aria-modal="true"><header><div><span className="eyebrow">Detalhes da OP</span><h2>{detalhe.ordemPagamento.numero}</h2></div><button aria-label="Fechar detalhes" onClick={()=>setDetalhe(null)}>×</button></header><div className="porto-detail-summary"><span>Previsto<strong>{moeda(detalhe.ordemPagamento.valorTotal)}</strong></span><span>Soma das OS<strong>{moeda(detalhe.ordemPagamento.valorOrdensServico)}</strong></span><span>Diferença<strong>{moeda(detalhe.ordemPagamento.divergencia)}</strong></span></div><div className="table-scroll"><table><thead><tr><th>OS</th><th>Especialidade</th><th>Data</th><th>Valor</th></tr></thead><tbody>{detalhe.ordensServico.map(os=><tr key={os.id}><td>{os.numero}</td><td>{os.especialidade}</td><td>{data(os.dataAtendimento)}</td><td>{moeda(os.valorTotal)}</td></tr>)}</tbody></table></div>{detalhe.ordemPagamento.divergencia!==0?<form className="porto-justification" onSubmit={justificar}><label className="field"><span>Motivo</span><select name="motivo" required><option value="">Selecione</option><option value="SERVICO_NAO_INCLUIDO">Serviço ainda não incluído</option><option value="DESCONTO">Desconto</option><option value="AJUSTE_PORTO">Ajuste da Porto</option><option value="SERVICO_PENDENTE">Serviço pendente</option><option value="SERVICO_DEVOLVIDO">Serviço devolvido</option><option value="DIVERGENCIA_VALOR">Divergência de valor</option><option value="OUTRO">Outro</option></select></label><label className="field"><span>Observação</span><textarea name="observacao" required/></label><button className="button button-primary">Registrar justificativa</button></form>:null}</section></div>:null}
  </div>
}
