insert into categorias(nome,tipo,ativo)
select 'Comissão de funcionário','DESPESA',true
where not exists (select 1 from categorias where lower(nome)=lower('Comissão de funcionário') and tipo='DESPESA');

create table pagamentos_comissao (
    id bigint generated by default as identity primary key,
    motorista_id bigint not null references motoristas(id),
    calendario_pagamento_id bigint not null references calendario_pagamentos_porto(id),
    despesa_id bigint not null unique references despesas(id),
    valor_pago numeric(12,2) not null check (valor_pago > 0),
    data_pagamento date not null,
    forma_pagamento text,
    observacoes text,
    pago_por_id bigint not null references usuarios(id),
    criado_em timestamp with time zone not null default current_timestamp,
    constraint pagamentos_comissao_periodo_uk unique (motorista_id, calendario_pagamento_id)
);

create index pagamentos_comissao_motorista_idx on pagamentos_comissao(motorista_id);
create index pagamentos_comissao_calendario_idx on pagamentos_comissao(calendario_pagamento_id);
create index pagamentos_comissao_data_idx on pagamentos_comissao(data_pagamento);
