-- Aluguel, seguro, parcela do guincho: valor fixo que cai todo mes. Antes da recorrencia, a unica
-- forma era redigitar tudo, e o que nao era digitado sumia do resultado.
create table despesas_recorrentes (
    id bigint generated by default as identity primary key,
    descricao text not null,
    categoria_id bigint not null references categorias(id),
    valor numeric(12,2) not null check (valor >= 0),
    dia_vencimento integer not null check (dia_vencimento between 1 and 31),
    veiculo_id bigint references veiculos(id),
    motorista_id bigint references motoristas(id),
    observacoes text,
    ativo boolean not null default true,
    criado_em timestamp with time zone not null default current_timestamp
);

-- Marca a despesa gerada pela recorrencia: e o que impede lancar o mesmo mes duas vezes.
alter table despesas add column despesa_recorrente_id bigint references despesas_recorrentes(id);
create index despesas_recorrente_idx on despesas(despesa_recorrente_id, vencimento);
