drop table if exists chamados;
drop table if exists clientes;
drop table if exists funcionarios;

create table usuarios (
    id bigint generated by default as identity primary key,
    nome text not null,
    email text not null unique,
    senha_hash text not null,
    perfil text not null check (perfil in ('ADMINISTRADOR','FUNCIONARIO')),
    ativo boolean not null default true,
    criado_em timestamp with time zone not null default current_timestamp
);

create table sessoes (
    id bigint generated by default as identity primary key,
    usuario_id bigint not null references usuarios(id) on delete cascade,
    token_hash text not null unique,
    expira_em timestamp with time zone not null,
    criado_em timestamp with time zone not null default current_timestamp
);

create table motoristas (
    id bigint generated by default as identity primary key,
    nome text not null,
    telefone text,
    documento text,
    usuario_id bigint references usuarios(id),
    ativo boolean not null default true
);

create table veiculos (
    id bigint generated by default as identity primary key,
    identificacao text not null,
    placa text not null unique,
    modelo text,
    custo_por_km numeric(12,4) not null default 0 check (custo_por_km >= 0),
    ativo boolean not null default true
);

create table contratantes (
    id bigint generated by default as identity primary key,
    nome text not null,
    documento text,
    ativo boolean not null default true
);

create table categorias (
    id bigint generated by default as identity primary key,
    nome text not null,
    tipo text not null check (tipo in ('RECEITA','DESPESA')),
    ativo boolean not null default true,
    unique (nome, tipo)
);

create table importacoes (
    id bigint generated by default as identity primary key,
    nome_arquivo text not null,
    hash_arquivo text not null unique,
    caminho_arquivo text not null,
    status text not null check (status in ('PROCESSANDO','AGUARDANDO_CONFERENCIA','CONFIRMADA','CANCELADA','ERRO_LEITURA')),
    texto_extraido text,
    mensagem_erro text,
    total_registros integer not null default 0,
    criado_em timestamp with time zone not null default current_timestamp,
    confirmado_em timestamp with time zone
);

create table itens_importacao (
    id bigint generated by default as identity primary key,
    importacao_id bigint not null references importacoes(id) on delete cascade,
    protocolo text,
    data_servico date,
    veiculo_atendido text,
    placa_atendida text,
    origem text,
    destino text,
    valor numeric(12,2),
    km_remunerado numeric(12,2),
    motorista_id bigint references motoristas(id),
    veiculo_id bigint references veiculos(id),
    previsao_pagamento date,
    observacoes text
);

create table contas_receber (
    id bigint generated by default as identity primary key,
    contratante_id bigint not null references contratantes(id),
    protocolo text,
    descricao text not null,
    valor_previsto numeric(12,2) not null check (valor_previsto >= 0),
    valor_recebido numeric(12,2),
    data_competencia date not null,
    vencimento date not null,
    data_recebimento date,
    status text not null check (status in ('PENDENTE','RECEBIDO','ATRASADO','CANCELADO')),
    veiculo_id bigint references veiculos(id),
    observacoes text,
    origem text not null check (origem in ('MANUAL','IMPORTADA')),
    importacao_id bigint references importacoes(id),
    criado_em timestamp with time zone not null default current_timestamp
);

create table receitas (
    id bigint generated by default as identity primary key,
    conta_receber_id bigint unique references contas_receber(id),
    contratante_id bigint references contratantes(id),
    categoria_id bigint references categorias(id),
    descricao text not null,
    valor numeric(12,2) not null check (valor >= 0),
    data_competencia date not null,
    data_recebimento date,
    status text not null check (status in ('PREVISTA','RECEBIDA','CANCELADA')),
    recorrente boolean not null default false,
    veiculo_id bigint references veiculos(id),
    observacoes text
);

create table despesas (
    id bigint generated by default as identity primary key,
    descricao text not null,
    categoria_id bigint not null references categorias(id),
    valor numeric(12,2) not null check (valor >= 0),
    data_lancamento date not null,
    vencimento date,
    data_pagamento date,
    forma_pagamento text,
    veiculo_id bigint references veiculos(id),
    motorista_id bigint references motoristas(id),
    protocolo text,
    comprovante text,
    observacoes text,
    status text not null check (status in ('PENDENTE','PAGO','ATRASADO','REJEITADO')),
    aprovada boolean not null default false,
    criado_por_id bigint not null references usuarios(id),
    aprovado_por_id bigint references usuarios(id),
    criado_em timestamp with time zone not null default current_timestamp
);

create table quilometragens (
    id bigint generated by default as identity primary key,
    data_registro date not null,
    veiculo_id bigint not null references veiculos(id),
    motorista_id bigint references motoristas(id),
    protocolo text,
    hodometro_inicial numeric(12,2) not null,
    hodometro_final numeric(12,2) not null,
    km_total numeric(12,2) not null,
    km_remunerado numeric(12,2) not null,
    km_morto numeric(12,2) not null,
    custo_por_km numeric(12,4) not null,
    custo_km_morto numeric(12,2) not null,
    observacoes text,
    unique (data_registro, veiculo_id, hodometro_inicial, hodometro_final)
);

create index sessoes_usuario_id_idx on sessoes(usuario_id);
create index motoristas_usuario_id_idx on motoristas(usuario_id);
create index itens_importacao_importacao_id_idx on itens_importacao(importacao_id);
create index contas_receber_contratante_id_idx on contas_receber(contratante_id);
create index contas_receber_veiculo_id_idx on contas_receber(veiculo_id);
create index contas_receber_importacao_id_idx on contas_receber(importacao_id);
create index receitas_conta_receber_id_idx on receitas(conta_receber_id);
create index receitas_veiculo_id_idx on receitas(veiculo_id);
create index despesas_categoria_id_idx on despesas(categoria_id);
create index despesas_veiculo_id_idx on despesas(veiculo_id);
create index despesas_motorista_id_idx on despesas(motorista_id);
create index quilometragens_veiculo_id_idx on quilometragens(veiculo_id);
create index quilometragens_motorista_id_idx on quilometragens(motorista_id);
