alter table importacoes add column tipo_relatorio_porto text;

create table ordens_pagamento_porto (
    id bigint generated by default as identity primary key,
    numero text not null unique,
    valor_total numeric(12,2) not null default 0,
    nome_codigo text,
    data_pagamento_programada date,
    valor_recebido numeric(12,2),
    data_recebimento date,
    importacao_id bigint references importacoes(id),
    criado_em timestamp with time zone not null default current_timestamp,
    atualizado_em timestamp with time zone not null default current_timestamp
);

create table ordens_servico_porto (
    id bigint generated by default as identity primary key,
    ordem_pagamento_id bigint references ordens_pagamento_porto(id),
    numero text not null unique,
    valor_total numeric(12,2) not null default 0,
    especialidade text,
    sigla_viatura text,
    socorrista text,
    qra text,
    data_atendimento date,
    valor_km_excedente numeric(12,2),
    km_morto_estimado numeric(12,2),
    importacao_id bigint references importacoes(id),
    criado_em timestamp with time zone not null default current_timestamp,
    atualizado_em timestamp with time zone not null default current_timestamp
);

create table pendencias_financeiras_porto (
    id bigint generated by default as identity primary key,
    ordem_servico_id bigint not null unique references ordens_servico_porto(id),
    tipo text not null,
    valor numeric(12,2) not null default 0,
    data_devolucao date not null,
    status text not null check (status in ('ABERTA','RESOLVIDA')),
    importacao_id bigint references importacoes(id),
    criado_em timestamp with time zone not null default current_timestamp
);

create table registros_importados_porto (
    id bigint generated by default as identity primary key,
    importacao_id bigint not null references importacoes(id) on delete cascade,
    hash_registro text not null unique,
    tipo_relatorio text not null,
    criado_em timestamp with time zone not null default current_timestamp
);

create index ordens_servico_porto_op_idx on ordens_servico_porto(ordem_pagamento_id);
create index pendencias_financeiras_porto_status_idx on pendencias_financeiras_porto(status);
