alter table ordens_servico_porto add column status_operacional text not null default 'NORMAL'
    check (status_operacional in ('NORMAL','PENDENTE_PORTO','DEVOLVIDO_FINALIZADO'));
alter table ordens_servico_porto add column status_financeiro text not null default 'AGUARDANDO_OP'
    check (status_financeiro in ('AGUARDANDO_OP','PAGAMENTO_PROGRAMADO','RECEBIDO','BLOQUEADO_PARA_PAGAMENTO','VALOR_DIVERGENTE'));
alter table ordens_servico_porto add column origem_importacao text not null default 'PORTO';
alter table ordens_servico_porto add column data_importacao timestamp with time zone not null default current_timestamp;
alter table ordens_servico_porto add column data_devolucao date;
alter table ordens_servico_porto add column data_finalizacao_devolucao date;

create table justificativas_conciliacao_porto (
    id bigint generated by default as identity primary key,
    ordem_pagamento_id bigint not null references ordens_pagamento_porto(id),
    motivo text not null check (motivo in ('SERVICO_NAO_INCLUIDO','DESCONTO','AJUSTE_PORTO','SERVICO_PENDENTE','SERVICO_DEVOLVIDO','DIVERGENCIA_VALOR','OUTRO')),
    observacao text,
    usuario_id bigint not null references usuarios(id),
    criado_em timestamp with time zone not null default current_timestamp
);

create index justificativas_conciliacao_porto_op_idx on justificativas_conciliacao_porto(ordem_pagamento_id);
create index ordens_servico_porto_status_idx on ordens_servico_porto(status_operacional,status_financeiro);
