create table calendario_pagamentos_porto (
    id bigint generated by default as identity primary key,
    data_pagamento date not null unique,
    descricao text not null,
    ativo boolean not null default true,
    criado_em timestamp with time zone not null default current_timestamp,
    atualizado_em timestamp with time zone not null default current_timestamp
);

insert into calendario_pagamentos_porto (data_pagamento, descricao) values
    ('2026-08-14', '1º ciclo de agosto de 2026'),
    ('2026-08-28', '2º ciclo de agosto de 2026'),
    ('2026-09-16', '1º ciclo de setembro de 2026'),
    ('2026-09-30', '2º ciclo de setembro de 2026'),
    ('2026-10-16', '1º ciclo de outubro de 2026'),
    ('2026-10-30', '2º ciclo de outubro de 2026'),
    ('2026-11-16', '1º ciclo de novembro de 2026'),
    ('2026-11-30', '2º ciclo de novembro de 2026'),
    ('2026-12-14', '1º ciclo de dezembro de 2026'),
    ('2026-12-30', '2º ciclo de dezembro de 2026');

alter table ordens_pagamento_porto add column status_porto text;
alter table ordens_pagamento_porto add column situacao_financeira text not null default 'PROGRAMADO';
alter table ordens_pagamento_porto add column observacao text;
alter table ordens_pagamento_porto add column calendario_pagamento_id bigint references calendario_pagamentos_porto(id);

alter table ordens_servico_porto add column prestador text;
alter table ordens_servico_porto add column seguradora text;
alter table ordens_servico_porto add column cliente text;
alter table ordens_servico_porto add column placa text;
alter table ordens_servico_porto add column data_hora_atendimento timestamp with time zone;
alter table ordens_servico_porto add column data_prevista_original date;
alter table ordens_servico_porto add column data_efetiva_pagamento date;
alter table ordens_servico_porto add column ciclos_atraso integer not null default 0;
alter table ordens_servico_porto add column status_operacional_fluxo text not null default 'NORMAL';
alter table ordens_servico_porto add column status_financeiro_fluxo text not null default 'AGUARDANDO_OP';
update ordens_servico_porto set status_operacional_fluxo=status_operacional, status_financeiro_fluxo=status_financeiro;

alter table justificativas_conciliacao_porto add column valor_diferenca numeric(12,2);
alter table importacoes add column usuario_id bigint references usuarios(id);
alter table importacoes add column ordem_pagamento_porto_id bigint references ordens_pagamento_porto(id);
alter table importacoes add column valor_total_porto numeric(12,2);
alter table importacoes add column registros_novos_porto integer not null default 0;
alter table importacoes add column registros_atualizados_porto integer not null default 0;
alter table importacoes add column registros_duplicados_porto integer not null default 0;
alter table importacoes add column registros_divergentes_porto integer not null default 0;
alter table importacoes add column registros_erros_porto integer not null default 0;

create table historico_porto (
    id bigint generated by default as identity primary key,
    ordem_pagamento_id bigint references ordens_pagamento_porto(id),
    ordem_servico_id bigint references ordens_servico_porto(id),
    usuario_id bigint references usuarios(id),
    evento text not null,
    descricao text not null,
    criado_em timestamp with time zone not null default current_timestamp,
    check (ordem_pagamento_id is not null or ordem_servico_id is not null)
);

create index calendario_pagamentos_porto_ativo_data_idx on calendario_pagamentos_porto(ativo, data_pagamento);
create index ordens_pagamento_porto_calendario_idx on ordens_pagamento_porto(calendario_pagamento_id);
create index ordens_servico_porto_previsao_idx on ordens_servico_porto(status_financeiro_fluxo, data_prevista_original);
create index importacoes_usuario_idx on importacoes(usuario_id);
create index importacoes_op_porto_idx on importacoes(ordem_pagamento_porto_id);
create index historico_porto_op_idx on historico_porto(ordem_pagamento_id, criado_em);
create index historico_porto_os_idx on historico_porto(ordem_servico_id, criado_em);
create index historico_porto_usuario_idx on historico_porto(usuario_id);
